=== MobiFlight/MobiFlight-Connector/MidiBoards/mfmidiboard.schema.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/mfmidiboard.schema.json",
  "title": "Root",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "Inputs",
    "InstanceName"
  ],
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "DifferingOutputName": {
      "$id": "#root/DifferingOutputName",
      "title": "DifferingOutputName",
      "type": "string",
      "description": "Name of the midi output port, if different from input name. Optional."
    },
    "EncoderNeutralPosition": {
      "$id": "#root/EncoderNeutralPosition",
      "title": "EncoderNeutralPosition",
      "type": "integer",
      "description": "Set the encoder neutral position. For example 0 or 64 Optional."
    },
    "InitialLayer": {
      "$id": "#root/InitialLayer",
      "title": "InitialLayer",
      "type": "string",
      "description": "When layer property is used, initial active layer on startup. Optional."
    },
    "Inputs": {
      "type": "array",
      "description": "List of inputs supported by the device. Required.",
      "items": {
        "$ref": "#/definitions/Input"
      },
      "minLength": 1
    },
    "Outputs": {
      "type": "array",
      "description": "List of LED outputs supported by the device. Optional.",
      "items": {
        "$ref": "#/definitions/Output"
      }
    }
  },
  "definitions": {
    "Input": {
      "type": "object",
      "title": "Input",
      "required": [
        "InputType",
        "Label",
        "LabelIds",
        "MessageChannel",
        "MessageIds",
        "MessageType"
      ],
      "additionalProperties": false,
      "properties": {
        "Label": {
          "$id": "#Input/Label",
          "type": "string",
          "description": "Friendly label for the input. Required.",
          "pattern": ".*%.*"
        },
        "LabelIds": {
          "$id": "#Input/LabelIds",
          "type": "array",
          "items": {
            "type": "string",
            "description": "Friendly label ids for the input, replacing the % in the label. Required."
          },
          "minLength": 1
        },
        "Layer": {
          "$id": "#Input/Layer",
          "type": "string",
          "description": "Associated layer for the input. Optional."
        },
        "InputType": {
          "$id": "#Input/InputType",
          "type": "string",
          "description": "The input's type. Supported values: Button, EndlessKnob, LimitedKnob, Fader, Pitch. Required.",
          "enum": [ "Button", "EndlessKnob", "LimitedKnob", "Fader", "Pitch" ]
        },
        "MessageType": {
          "$id": "#Input/MessageType",
          "type": "string",
          "description": "The midi message type. Supported values: Note, CC, Pitch. Required.",
          "enum": [ "Note", "CC", "Pitch" ]
        },
        "MessageChannel": {
          "$id": "#Input/MessageChannel",
          "type": "integer",
          "description": "The midi message channel. Possible value range from 1 to 16. Required."
        },
        "MessageIds": {
          "$id": "#Input/MessageIds",
          "type": "array",
          "description": "The midi message ids. Possible value range from 0 to 127. Required.",
          "items": {
            "type": "integer"
          },
          "minLength": 1
        }
      }
    },
    "Output": {
      "type": "object",
      "title": "Output",
      "additionalProperties": false,
      "required": [
        "Label",
        "LabelIds",
        "MessageChannel",
        "MessageIds",
        "MessageType",
        "ValueOff",
        "ValueOn"
      ],
      "properties": {
        "Label": {
          "$id": "#Output/Label",
          "type": "string",
          "description": "Friendly label for the output. Required.",
          "pattern": ".*%.*"
        },
        "LabelIds": {
          "$id": "#Output/LabelIds",
          "type": "array",
          "items": {
            "type": "string",
            "description": "Friendly label ids for the output, replacing the % in the label. Required."
          },
          "minLength": 1
        },
        "Layer": {
          "$id": "#Output/Layer",
          "type": "string",
          "description": "Associated layer for the output. Optional."
        },
        "MessageType": {
          "$id": "#Output/MessageType",
          "type": "string",
          "description": "The midi message type. Supported values: Note, CC. Required.",
          "enum": [ "Note", "CC" ]
        },
        "MessageChannel": {
          "$id": "#Output/MessageChannel",
          "type": "integer",
          "description": "The midi message channel. Possible value range from 1 to 16. Required."
        },
        "MessageIds": {
          "$id": "#Output/MessageIds",
          "type": "array",
          "description": "The midi message ids. Possible value range from 0 to 127. Required.",
          "items": {
            "type": "integer"
          },
          "minLength": 1
        },
        "ValueOn": {
          "$id": "#Output/ValueOn",
          "type": "integer",
          "description": "Midi message value for turning on the LED. Required."
        },
        "ValueBlinkOn": {
          "$id": "#Output/ValueBlinkOn",
          "type": "integer",
          "description": "Midi message value for putting LED to blink mode. Optional."
        },
        "ValueOff": {
          "$id": "#Output/ValueOff",
          "type": "integer",
          "description": "Midi message value for turning off the LED. Required."
        },
        "RelatedInputLabel": {
          "$id": "#Output/RelatedInputLabel",
          "type": "string",
          "description": "Label of related input. When related input is triggered, output is auto refreshed. Optional.",
          "pattern": ".*%.*"
        },
        "RelatedIds": {
          "$id": "#Output/RelatedIds",
          "type": "array",
          "description": "Label ids of related input, replacing the % in the related input label. Optional.",
          "items": {
            "type": "string"
          },
          "minLength": 1
        }
      }
    }
  }
}

=== MobiFlight/MobiFlight-Connector/MidiBoards/akai/mpd218.midiboard.json
{
  "$schema": "./mfmidiboard.schema.json",
  "InstanceName": "MPD218",
  "EncoderNeutralPosition": 0,
  "Inputs": [
    {
      "Label": "Knob % - Bank A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6" ],
      "InputType": "EndlessKnob",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 3, 9, 12, 13, 14, 15 ]
    },
    {
      "Label": "Pad % - Bank A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51 ]
    },
    {
      "Label": "Knob % - Bank B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6" ],
      "InputType": "EndlessKnob",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 16, 17, 18, 19, 20, 21 ]
    },
    {
      "Label": "Pad % - Bank B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67 ]
    },
    {
      "Label": "Knob % - Bank C",
      "LabelIds": [ "1", "2", "3", "4", "5", "6" ],
      "InputType": "EndlessKnob",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 22, 23, 24, 25, 26, 27 ]
    },
    {
      "Label": "Pad % - Bank C",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83 ]
    }
  ],
  "Outputs": [
    {
      "Label": "LED Pad % - Bank A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51 ],
      "ValueOn": 127,
      "ValueOff": 0,
      "RelatedInputLabel": "Pad % - Bank A",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ]
    },
    {
      "Label": "LED Pad % - Bank B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67 ],
      "ValueOn": 127,
      "ValueOff": 0,
      "RelatedInputLabel": "Pad % - Bank B",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ]
    },
    {
      "Label": "LED Pad % - Bank C",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "MessageType": "Note",
      "MessageChannel": 10,
      "MessageIds": [ 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83 ],
      "ValueOn": 127,
      "ValueOff": 0,
      "RelatedInputLabel": "Pad % - Bank C",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ]
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/MidiBoards/x_touch_mini.midiboard.json
{
  "$schema": "./mfmidiboard.schema.json",
  "InstanceName": "X-TOUCH MINI",
  "EncoderNeutralPosition": 64,
  "InitialLayer": "A",
  "Inputs": [
    {
      "Label": "Button % - Layer A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "Layer": "A",
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 11,
      "MessageIds": [ 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 ]
    },
    {
      "Label": "Button Encoder % - Layer A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "A",
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 11,
      "MessageIds": [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    },
    {
      "Label": "Encoder % - Layer A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "A",
      "InputType": "EndlessKnob",
      "MessageType": "CC",
      "MessageChannel": 11,
      "MessageIds": [ 1, 2, 3, 4, 5, 6, 7, 8 ]
    },
    {
      "Label": "Fader % - Layer A",
      "LabelIds": [ "1" ],
      "Layer": "A",
      "InputType": "Fader",
      "MessageType": "CC",
      "MessageChannel": 11,
      "MessageIds": [ 0 ]
    },
    {
      "Label": "Button % - Layer B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "Layer": "B",
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 11,
      "MessageIds": [ 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47 ]
    },
    {
      "Label": "Button Encoder % - Layer B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "B",
      "InputType": "Button",
      "MessageType": "Note",
      "MessageChannel": 11,
      "MessageIds": [ 24, 25, 26, 27, 28, 29, 30, 31 ]
    },
    {
      "Label": "Encoder % - Layer B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "B",
      "InputType": "EndlessKnob",
      "MessageType": "CC",
      "MessageChannel": 11,
      "MessageIds": [ 11, 12, 13, 14, 15, 16, 17, 18 ]
    },
    {
      "Label": "Fader % - Layer B",
      "LabelIds": [ "1" ],
      "Layer": "B",
      "InputType": "Fader",
      "MessageType": "CC",
      "MessageChannel": 11,
      "MessageIds": [ 10 ]
    }
  ],
  "Outputs": [
    {
      "Label": "LED Button % - Layer A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "Layer": "A",
      "MessageType": "Note",
      "MessageChannel": 1,
      "MessageIds": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ],
      "ValueOn": 1,
      "ValueBlinkOn": 2,
      "ValueOff": 0,
      "RelatedInputLabel": "Button % - Layer A",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ]
    },
    {
      "Label": "LED Ring Encoder % - Layer A",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "A",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 9, 10, 11, 12, 13, 14, 15, 16 ],
      "ValueOn": 27,
      "ValueBlinkOn": 28,
      "ValueOff": 0,
      "RelatedInputLabel": "Encoder % - Layer A",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ]
    },
    {
      "Label": "LED Button % - Layer B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ],
      "Layer": "B",
      "MessageType": "Note",
      "MessageChannel": 1,
      "MessageIds": [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 ],
      "ValueOn": 1,
      "ValueBlinkOn": 2,
      "ValueOff": 0,
      "RelatedInputLabel": "Button % - Layer B",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16" ]
    },
    {
      "Label": "LED Ring Encoder % - Layer B",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "Layer": "B",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 9, 10, 11, 12, 13, 14, 15, 16 ],
      "ValueOn": 27,
      "ValueBlinkOn": 28,
      "ValueOff": 0,
      "RelatedInputLabel": "Encoder % - Layer B",
      "RelatedIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ]
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/MidiBoards/nanokontrol2.midiboard.json
{
  "$schema": "./mfmidiboard.schema.json",
  "InstanceName": "nanoKONTROL2 1 SLIDER/KNOB",
  "DifferingOutputName": "nanoKONTROL2 1 CTRL",
  "Inputs": [
    {
      "Label": "Knob %",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "InputType": "LimitedKnob",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 16, 17, 18, 19, 20, 21, 22, 23 ]
    },
    {
      "Label": "Button S%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "InputType": "Button",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 32, 33, 34, 35, 36, 37, 38, 39 ]
    },
    {
      "Label": "Button M%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "InputType": "Button",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 48, 49, 50, 51, 52, 53, 54, 55 ]
    },
    {
      "Label": "Button R%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "InputType": "Button",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 64, 65, 66, 67, 68, 69, 70, 71 ]
    },
    {
      "Label": "Slider %",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "InputType": "Fader",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 0, 1, 2, 3, 4, 5, 6, 7 ]
    },
    {
      "Label": "Button %",
      "LabelIds": [ "Cycle", "Backward", "Forward", "Stop", "Play", "Record" ],
      "InputType": "Button",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 46, 43, 44, 42, 41, 45 ]
    },
    {
      "Label": "Button %",
      "LabelIds": [ "Prev Track", "Next Track", "Set Marker", "Prev Marker", "Next Marker" ],
      "InputType": "Button",
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 58, 59, 60, 61, 62 ]
    }
  ],
  "Outputs": [
    {
      "Label": "LED Button S%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 32, 33, 34, 35, 36, 37, 38, 39 ],
      "ValueOn": 127,
      "ValueOff": 0
    },
    {
      "Label": "LED Button M%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 48, 49, 50, 51, 52, 53, 54, 55 ],
      "ValueOn": 127,
      "ValueOff": 0
    },
    {
      "Label": "LED Button R%",
      "LabelIds": [ "1", "2", "3", "4", "5", "6", "7", "8" ],
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 64, 65, 66, 67, 68, 69, 70, 71 ],
      "ValueOn": 127,
      "ValueOff": 0
    },
    {
      "Label": "LED Button %",
      "LabelIds": [ "Cycle", "Backward", "Forward", "Stop", "Play", "Record" ],
      "MessageType": "CC",
      "MessageChannel": 1,
      "MessageIds": [ 46, 43, 44, 42, 41, 45 ],
      "ValueOn": 127,
      "ValueOff": 0
    }
  ]
}
