=== MobiFlight/MobiFlight-Connector/Joysticks/mfhid.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": ["InstanceName"],
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": ["Name", "Label"],
        "properties": {
          "Name": {
            "$id": "#root/Inputs/items/Name",
            "title": "Name",
            "description": "Device's name for the input.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Label for the input.",
            "type": "string"
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": ["Name", "Label"],
        "properties": {
          "Name": {
            "$id": "#root/Inputs/items/Name",
            "title": "Name",
            "description": "Device's name for the input.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Label for the input.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Inputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Inputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output.",
            "type": "number"
          }
        }
      }
    },
    "ProductId": {
      "$id": "#Root/InstanceName",
      "title": "InstanceName",
      "type": "number",
      "description": "Instance name for the device. This is used to match the definition with a connected device."
    },
    "VendorId": {
      "$id": "#Root/InstanceName",
      "title": "InstanceName",
      "type": "number",
      "description": "Instance name for the device. This is used to match the definition with a connected device."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/Joysticks/honeycomb_bravo.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "Bravo Throttle Quadrant",
  "VendorId": 10571,
  "ProductId": 6401,
  "Inputs": [
    {
      "Name": "Button 17",
      "Label": "Mode - IAS"
    },
    {
      "Name": "Button 18",
      "Label": "Mode - CRS"
    },
    {
      "Name": "Button 19",
      "Label": "Mode - HDG"
    },
    {
      "Name": "Button 20",
      "Label": "Mode - VS"
    },
    {
      "Name": "Button 21",
      "Label": "Mode - ALT"
    },
    {
      "Name": "Button 1",
      "Label": "AP - HDG"
    },
    {
      "Name": "Button 2",
      "Label": "AP - NAV"
    },
    {
      "Name": "Button 3",
      "Label": "AP - APR"
    },
    {
      "Name": "Button 4",
      "Label": "AP - REV"
    },
    {
      "Name": "Button 5",
      "Label": "AP - ALT"
    },
    {
      "Name": "Button 6",
      "Label": "AP - VS"
    },
    {
      "Name": "Button 7",
      "Label": "AP - IAS"
    },
    {
      "Name": "Button 8",
      "Label": "AP - Autopilot"
    },
    {
      "Name": "Button 13",
      "Label": "Encoder - Right"
    },
    {
      "Name": "Button 14",
      "Label": "Encoder - Left"
    },
    {
      "Name": "Button 31",
      "Label": "Gear - Up"
    },
    {
      "Name": "Button 32",
      "Label": "Gear - Down"
    },
    {
      "Name": "Button 16",
      "Label": "Flaps - Up"
    },
    {
      "Name": "Button 15",
      "Label": "Flaps - Down"
    },
    {
      "Name": "Button 22",
      "Label": "Trim - Nose Down"
    },
    {
      "Name": "Button 23",
      "Label": "Trim - Nose Up"
    },
    {
      "Name": "Button 24",
      "Label": "Lever 1 - Detent"
    },
    {
      "Name": "Button 25",
      "Label": "Lever 2 - Detent"
    },
    {
      "Name": "Button 26",
      "Label": "Lever 3 - Detent"
    },
    {
      "Name": "Button 27",
      "Label": "Lever 4 - Detent"
    },
    {
      "Name": "Button 28",
      "Label": "Lever 5 - Detent"
    },
    {
      "Name": "Button 33",
      "Label": "Lever 6 - Detent"
    },
    {
      "Name": "Button 29",
      "Label": "Lever 1 - Button"
    },
    {
      "Name": "Button 9",
      "Label": "Lever 2 - Button"
    },
    {
      "Name": "Button 10",
      "Label": "Lever 3 - Button"
    },
    {
      "Name": "Button 11",
      "Label": "Lever 4 - Button"
    },
    {
      "Name": "Button 12",
      "Label": "Lever 5 - Button"
    },
    {
      "Name": "Button 30",
      "Label": "Lever 3 - Reverser"
    },
    {
      "Name": "Button 48",
      "Label": "Lever 4 - Reverser"
    },
    {
      "Name": "Button 34",
      "Label": "Switch 1 - Up"
    },
    {
      "Name": "Button 35",
      "Label": "Switch 1 - Down"
    },
    {
      "Name": "Button 36",
      "Label": "Switch 2 - Up"
    },
    {
      "Name": "Button 37",
      "Label": "Switch 2 - Down"
    },
    {
      "Name": "Button 38",
      "Label": "Switch 3 - Up"
    },
    {
      "Name": "Button 39",
      "Label": "Switch 3 - Down"
    },
    {
      "Name": "Button 40",
      "Label": "Switch 4 - Up"
    },
    {
      "Name": "Button 41",
      "Label": "Switch 4 - Down"
    },
    {
      "Name": "Button 42",
      "Label": "Switch 5 - Up"
    },
    {
      "Name": "Button 43",
      "Label": "Switch 5 - Down"
    },
    {
      "Name": "Button 44",
      "Label": "Switch 6 - Up"
    },
    {
      "Name": "Button 45",
      "Label": "Switch 6 - Down"
    },
    {
      "Name": "Button 46",
      "Label": "Switch 7 - Up"
    },
    {
      "Name": "Button 47",
      "Label": "Switch 7 - Down"
    },
    {
      "Name": "Y Axis",
      "Label": "Axis - Lever 1"
    },
    {
      "Name": "X Axis",
      "Label": "Axis - Lever 2"
    },
    {
      "Name": "Z Rotation",
      "Label": "Axis - Lever 3"
    },
    {
      "Name": "Y Rotation",
      "Label": "Axis - Lever 4"
    },
    {
      "Name": "X Rotation",
      "Label": "Axis - Lever 5"
    },
    {
      "Name": "Z Axis",
      "Label": "Axis - Lever 6"
    }
  ],
  "Outputs": [
    {
      "Label": "AP Mode - HDG",
      "Name": "AP.hdg",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "AP Mode - NAV",
      "Name": "AP.nav",
      "Byte": 1,
      "Bit": 1
    },
    {
      "Label": "AP Mode - APR",
      "Name": "AP.apr",
      "Byte": 1,
      "Bit": 2
    },
    {
      "Label": "AP Mode - REV",
      "Name": "AP.rev",
      "Byte": 1,
      "Bit": 3
    },
    {
      "Label": "AP Mode - ALT",
      "Name": "AP.alt",
      "Byte": 1,
      "Bit": 4
    },
    {
      "Label": "AP Mode - VS",
      "Name": "AP.vs",
      "Byte": 1,
      "Bit": 5
    },
    {
      "Label": "AP Mode - IAS",
      "Name": "AP.ias",
      "Byte": 1,
      "Bit": 6
    },
    {
      "Label": "AP Mode - On/Off",
      "Name": "AP.autopilot",
      "Byte": 1,
      "Bit": 7
    },
    {
      "Label": "Gear - Left Green",
      "Name": "Gear.LeftGreen",
      "Byte": 2,
      "Bit": 0
    },
    {
      "Label": "Gear - Left Red",
      "Name": "Gear.LeftRed",
      "Byte": 2,
      "Bit": 1
    },
    {
      "Label": "Gear - Center Green",
      "Name": "Gear.CenterGreen",
      "Byte": 2,
      "Bit": 2
    },
    {
      "Label": "Gear - Center Red",
      "Name": "Gear.CenterRed",
      "Byte": 2,
      "Bit": 3
    },
    {
      "Label": "Gear - Right Green",
      "Name": "Gear.RightGreen",
      "Byte": 2,
      "Bit": 4
    },
    {
      "Label": "Gear - Right Red",
      "Name": "Gear.RightRed",
      "Byte": 2,
      "Bit": 5
    },
    {
      "Label": "Lights - Master Warning",
      "Name": "Light.MasterWarn",
      "Byte": 2,
      "Bit": 6
    },
    {
      "Label": "Lights - Engine Fire",
      "Name": "Light.EngineFire",
      "Byte": 2,
      "Bit": 7
    },
    {
      "Label": "Lights - Low Oil Pressure",
      "Name": "Light.LowOil",
      "Byte": 3,
      "Bit": 0
    },
    {
      "Label": "Lights - Low Fuel Pressure",
      "Name": "Light.LowFuel",
      "Byte": 3,
      "Bit": 1
    },
    {
      "Label": "Lights - Anti Ice",
      "Name": "Light.Antiice",
      "Byte": 3,
      "Bit": 2
    },
    {
      "Label": "Lights - Starter Engaged",
      "Name": "Light.Starter",
      "Byte": 3,
      "Bit": 3
    },
    {
      "Label": "Lights - APU",
      "Name": "Light.APU",
      "Byte": 3,
      "Bit": 4
    },
    {
      "Label": "Lights - Master Caution",
      "Name": "Light.MasterCaution",
      "Byte": 3,
      "Bit": 5
    },
    {
      "Label": "Lights - Vacuum",
      "Name": "Light.Vacuum",
      "Byte": 3,
      "Bit": 6
    },
    {
      "Label": "Lights - Low Hyd Pressure",
      "Name": "Light.LowHydPressURE",
      "Byte": 3,
      "Bit": 7
    },
    {
      "Label": "Lights - Aux Fuel Pump",
      "Name": "Lights.AuxFuelPump",
      "Byte": 4,
      "Bit": 0
    },
    {
      "Label": "Lights - Parking Brake",
      "Name": "Lights.ParkingBrake",
      "Byte": 4,
      "Bit": 1
    },
    {
      "Label": "Lights - Low Volts",
      "Name": "Lights.LowVolts",
      "Byte": 4,
      "Bit": 2
    },
    {
      "Label": "Lights - Door",
      "Name": "Lights.door",
      "Byte": 4,
      "Bit": 3
    }
  ]
}
