=== MobiFlight/MobiFlight-Connector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": ["InstanceName"],
  "dependentRequired": {
    "Outputs": ["VendorId", "ProductId"]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type"],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": ["Id", "Label", "Byte", "Bit"],
        "properties": {
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required.",
            "type": "number"
          }
        }
      }
    },
    "ProductId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "VendorId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim/vkbsim_gladiator_evo_r_fsm_ga.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBsim Gladiator EVO R FSM.GA",
  "VendorId": "0x231D",
  "ProductId": "0x0220",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Trigger Soft"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Trigger Hard"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "A2"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "B1"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "D1"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A3 Up"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "A3 Right"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "A3 Down"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "A3 Left"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "A3 Push"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "A4 Up"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "A4 Right"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "A4 Down"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "A4 Left"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "A4 Push"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "C1 Up"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "C1 Right"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "C1 Down"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "C1 Left"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "C1 Push"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "Rapid Fire Up"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Rapid Fire Down"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "Sw1 Up"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "Sw1 Down"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "F1"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "F2"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "F3"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "A1 Push"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "Unused Button 31"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Unused Button 32"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "Unused Button 33"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "Unused Button 34"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "Unused Button 35"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "Unused Button 36"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "Unused Button 37"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "Unused Button 38"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "Unused Button 39"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "Unused Button 40"
    },
    {
      "Id": 1000,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 1005,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "FSM.GA HDG"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "FSM.GA TRK"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "FSM.GA NAV"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "FSM.GA APR"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "FSM.GA ALT"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "FSM.GA LVL"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "FSM.GA VNAV"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "FSM.GA IAS"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "FSM.GA AP"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "FSM.GA FD"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "FSM.GA YD"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "FSM.GA VS"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "FSM.GA Avionic"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "FSM.GA Landing Lights"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "FSM.GA Strobe"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "FSM.GA Nav Lights"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "FSM.GA HDG TRK CCW"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "FSM.GA HDG TRK CW"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "FSM.GA ALT SEL CCW"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "FSM.GA ALT SEL CW"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "FSM.GA VS Nose Down"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "FSM.GA VS Nose Up"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "FSM.GA HDG TRK Push"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "FSM.GA ALT SEL Push"
    },
    {
      "Id": 1010,
      "Type": "Button",
      "Label": "FSM.GA HDG TRK CCW"
    },
    {
      "Id": 1015,
      "Type": "Button",
      "Label": "FSM.GA HDG TRK CW"
    },
    {
      "Id": 1020,
      "Type": "Button",
      "Label": "FSM.GA ALT SEL CCW"
    },
    {
      "Id": 1025,
      "Type": "Button",
      "Label": "FSM.GA ALT SEL CW"
    },
    {
      "Id": 1030,
      "Type": "Button",
      "Label": "FSM.GA VS Nose Down"
    },
    {
      "Id": 1035,
      "Type": "Button",
      "Label": "FSM.GA VS Nose Up"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Red",
      "Id": "SCG.Oval.Red",
      "Byte": 10,
      "Bit": 0
    },
    {
      "Label": "SCG Oval - Green",
      "Id": "SCG.Oval.Green",
      "Byte": 10,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Blue",
      "Id": "SCG.Oval.Blue",
      "Byte": 10,
      "Bit": 2
    },
    {
      "Label": "SCG Round",
      "Id": "SCG.Round",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "FSM.GA HDG - Green",
      "Id": "FSMGA.HDG.Green",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "FSM.GA HDG - Red",
      "Id": "FSMGA.HDG.Red",
      "Byte": 12,
      "Bit": 1
    },
    {
      "Label": "FSM.GA TRK - Green",
      "Id": "FSMGA.TRK.Green",
      "Byte": 13,
      "Bit": 0
    },
    {
      "Label": "FSM.GA TRK - Red",
      "Id": "FSMGA.TRK.Red",
      "Byte": 13,
      "Bit": 1
    },
    {
      "Label": "FSM.GA NAV - Green",
      "Id": "FSMGA.NAV.Green",
      "Byte": 14,
      "Bit": 0
    },
    {
      "Label": "FSM.GA NAV - Red",
      "Id": "FSMGA.NAV.Red",
      "Byte": 14,
      "Bit": 1
    },
    {
      "Label": "FSM.GA APR - Green",
      "Id": "FSMGA.APR.Green",
      "Byte": 15,
      "Bit": 0
    },
    {
      "Label": "FSM.GA APR - Red",
      "Id": "FSMGA.APR.Red",
      "Byte": 15,
      "Bit": 1
    },
    {
      "Label": "FSM.GA ALT - Green",
      "Id": "FSMGA.ALT.Green",
      "Byte": 16,
      "Bit": 0
    },
    {
      "Label": "FSM.GA ALT - Red",
      "Id": "FSMGA.ALT.Red",
      "Byte": 16,
      "Bit": 1
    },
    {
      "Label": "FSM.GA LVL - Green",
      "Id": "FSMGA.LVL.Green",
      "Byte": 17,
      "Bit": 0
    },
    {
      "Label": "FSM.GA LVL - Red",
      "Id": "FSMGA.LVL.Red",
      "Byte": 17,
      "Bit": 1
    },
    {
      "Label": "FSM.GA VNAV - Green",
      "Id": "FSMGA.VNAV.Green",
      "Byte": 18,
      "Bit": 0
    },
    {
      "Label": "FSM.GA VNAV - Red",
      "Id": "FSMGA.VNAV.Red",
      "Byte": 18,
      "Bit": 1
    },
    {
      "Label": "FSM.GA IAS - Green",
      "Id": "FSMGA.IAS.Green",
      "Byte": 19,
      "Bit": 0
    },
    {
      "Label": "FSM.GA IAS - Red",
      "Id": "FSMGA.IAS.Red",
      "Byte": 19,
      "Bit": 1
    },
    {
      "Label": "FSM.GA AP - Green",
      "Id": "FSMGA.AP.Green",
      "Byte": 20,
      "Bit": 0
    },
    {
      "Label": "FSM.GA AP - Red",
      "Id": "FSMGA.AP.Red",
      "Byte": 20,
      "Bit": 1
    },
    {
      "Label": "FSM.GA FD - Green",
      "Id": "FSMGA.FD.Green",
      "Byte": 21,
      "Bit": 0
    },
    {
      "Label": "FSM.GA FD - Red",
      "Id": "FSMGA.FD.Red",
      "Byte": 21,
      "Bit": 1
    },
    {
      "Label": "FSM.GA YD - Green",
      "Id": "FSMGA.YD.Green",
      "Byte": 22,
      "Bit": 0
    },
    {
      "Label": "FSM.GA YD - Red",
      "Id": "FSMGA.YD.Red",
      "Byte": 22,
      "Bit": 1
    },
    {
      "Label": "FSM.GA VS - Green",
      "Id": "FSMGA.VS.Green",
      "Byte": 23,
      "Bit": 0
    },
    {
      "Label": "FSM.GA VS - Red",
      "Id": "FSMGA.VS.Red",
      "Byte": 23,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim_gladiator_evo_l_sem.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBsim Gladiator EVO L SEM",
  "VendorId": "0x231D",
  "ProductId": "0x0205",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Trigger Soft"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Trigger Hard"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "A2"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "B1"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "D1"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A3 Up"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "A3 Right"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "A3 Down"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "A3 Left"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "A3 Push"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "A4 Up"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "A4 Right"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "A4 Down"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "A4 Left"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "A4 Push"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "C1 Up"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "C1 Right"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "C1 Down"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "C1 Left"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "C1 Push"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "Rapid Fire Up"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Rapid Fire Down"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "Sw1 Up"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "Sw1 Down"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "F1"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "F2"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "F3"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "A1 Push"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "Unused Button 31"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Unused Button 32"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "Unused Button 33"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "Unused Button 34"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "Unused Button 35"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "Unused Button 36"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "Unused Button 37"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "Unused Button 38"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "Unused Button 39"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "Unused Button 40"
    },
    {
      "Id": 1000,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 1005,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "SEM A1"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "SEM A2"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "SEM B1"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "SEM B2"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "SEM B3"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "SEM Sw1 Up"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "SEM Sw1 Center"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "SEM Sw1 Down"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "SEM Sw2 Up"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "SEM Sw2 Center"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "SEM Sw2 Down"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "SEM Start"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "SEM Mode 1"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "SEM Mode 2"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "SEM Mode 3"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "SEM Mode 4"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "SEM C1"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "SEM Flaps 3"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "SEM Flaps 2"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "SEM Flaps 1"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "SEM Flaps 0"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "SEM Gear Down"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "SEM Gear Neutral"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "SEM Gear Up"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Red",
      "Id": "SCG.Oval.Red",
      "Byte": 10,
      "Bit": 0
    },
    {
      "Label": "SCG Oval - Green",
      "Id": "SCG.Oval.Green",
      "Byte": 10,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Blue",
      "Id": "SCG.Oval.Blue",
      "Byte": 10,
      "Bit": 2
    },
    {
      "Label": "SCG Round",
      "Id": "SCG.Round",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "SEM A1 - Green",
      "Id": "SEM.A1.Green",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "SEM A1 - Red",
      "Id": "SEM.A1.Red",
      "Byte": 12,
      "Bit": 1
    },
    {
      "Label": "SEM A2 - Green",
      "Id": "SEM.A2.Green",
      "Byte": 13,
      "Bit": 0
    },
    {
      "Label": "SEM A2 - Red",
      "Id": "SEM.A2.Red",
      "Byte": 13,
      "Bit": 1
    },
    {
      "Label": "SEM B1 - Green",
      "Id": "SEM.B1.Green",
      "Byte": 14,
      "Bit": 0
    },
    {
      "Label": "SEM B1 - Red",
      "Id": "SEM.B1.Red",
      "Byte": 14,
      "Bit": 1
    },
    {
      "Label": "SEM B2 - Green",
      "Id": "SEM.B2.Green",
      "Byte": 15,
      "Bit": 0
    },
    {
      "Label": "SEM B2 - Red",
      "Id": "SEM.B2.Red",
      "Byte": 15,
      "Bit": 1
    },
    {
      "Label": "SEM B3 - Green",
      "Id": "SEM.B3.Green",
      "Byte": 16,
      "Bit": 0
    },
    {
      "Label": "SEM B3 - Red",
      "Id": "SEM.B3.Red",
      "Byte": 16,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Left - Green",
      "Id": "SEM.GearL.Green",
      "Byte": 17,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Left - Red",
      "Id": "SEM.GearL.Red",
      "Byte": 17,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Center - Green",
      "Id": "SEM.GearC.Green",
      "Byte": 18,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Center - Red",
      "Id": "SEM.GearC.Red",
      "Byte": 18,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Right - Green",
      "Id": "SEM.GearR.Green",
      "Byte": 19,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Right - Red",
      "Id": "SEM.GearR.Red",
      "Byte": 19,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/flitesim_ffb.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "FliteSim FFB",
  "VendorId": "0x0000",
  "ProductId": "0x0000",
  "Inputs": [
    {
      "Id": 0,
      "Type": "Button",
      "Name": "Button 0",
      "Label": "Override pitch"
    },
    {
      "Id": 1,
      "Type": "Button",
      "Name": "Button 1",
      "Label": "Override roll"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Name": "Button 2",
      "Label": "Override heading"
    },
    {
      "Id": 3,
      "Type": "Axis",
      "Name": "Axis X",
      "Label": "Pitch ratio"
    },
    {
      "Id": 4,
      "Type": "Axis",
      "Name": "Axis Y",
      "Label": "Roll ratio"
    },
    {
      "Id": 5,
      "Type": "Axis",
      "Name": "Axis Z",
      "Label": "Heading ratio"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Name": "Button 6",
      "Label": "Pitch Trim Control"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Name": "Button 7",
      "Label": "Roll Trim Control"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Name": "Button 8",
      "Label": "Yaw Trim Control"
    },
    {
      "Id": 9,
      "Type": "Axis",
      "Name": "Axis RotationX",
      "Label": "Elevator trim"
    },
    {
      "Id": 10,
      "Type": "Axis",
      "Name": "Axis RotationY",
      "Label": "Aileron trim"
    },
    {
      "Id": 11,
      "Type": "Axis",
      "Name": "Axis RotationZ",
      "Label": "Rudder trim"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Name": "Button 12",
      "Label": "AP Auto Disconnect"
    }
  ],
  "Outputs": [
    {
      "Label": "Version",
      "Id": "Version",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sim Time",
      "Id": "Sim Time",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "Paused",
      "Id": "Paused",
      "Byte": 2,
      "Bit": 0
    },
    {
      "Label": "Mach Number",
      "Id": "Mach Number",
      "Byte": 3,
      "Bit": 0
    },
    {
      "Label": "AoA",
      "Id": "AoA",
      "Byte": 4,
      "Bit": 0
    },
    {
      "Label": "Vertical Speed",
      "Id": "Vertical Speed",
      "Byte": 5,
      "Bit": 0
    },
    {
      "Label": "Wind Speed",
      "Id": "Wind Speed",
      "Byte": 6,
      "Bit": 0
    },
    {
      "Label": "Wind Direction",
      "Id": "Wind Direction",
      "Byte": 7,
      "Bit": 0
    },
    {
      "Label": "Magnetic Heading",
      "Id": "Magnetic Heading",
      "Byte": 8,
      "Bit": 0
    },
    {
      "Label": "Surface Type",
      "Id": "Surface Type",
      "Byte": 9,
      "Bit": 0
    },
    {
      "Label": "Stall Warning",
      "Id": "Stall Warning",
      "Byte": 10,
      "Bit": 0
    },
    {
      "Label": "Radio Altitude",
      "Id": "Radio Altitude",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "Total Roll Input",
      "Id": "Total Roll Input",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "Total Pitch Input",
      "Id": "Total Pitch Input",
      "Byte": 13,
      "Bit": 0
    },
    {
      "Label": "Autopilot Mode",
      "Id": "Autopilot Mode",
      "Byte": 14,
      "Bit": 0
    },
    {
      "Label": "Has Crashed",
      "Id": "Has Crashed",
      "Byte": 15,
      "Bit": 0
    },
    {
      "Label": "Engine RPM 1",
      "Id": "Engine RPM 1",
      "Byte": 16,
      "Bit": 0
    },
    {
      "Label": "Engine RPM 2",
      "Id": "Engine RPM 2",
      "Byte": 17,
      "Bit": 0
    },
    {
      "Label": "Engine RPM 3",
      "Id": "Engine RPM 3",
      "Byte": 18,
      "Bit": 0
    },
    {
      "Label": "Engine RPM 4",
      "Id": "Engine RPM 4",
      "Byte": 19,
      "Bit": 0
    },
    {
      "Label": "Gear 1 On Ground",
      "Id": "Gear 1 On Ground",
      "Byte": 20,
      "Bit": 0
    },
    {
      "Label": "Gear 2 On Ground",
      "Id": "Gear 2 On Ground",
      "Byte": 21,
      "Bit": 0
    },
    {
      "Label": "Gear 3 On Ground",
      "Id": "Gear 3 On Ground",
      "Byte": 22,
      "Bit": 0
    },
    {
      "Label": "Elevator Trim",
      "Id": "Elevator Trim",
      "Byte": 23,
      "Bit": 0
    },
    {
      "Label": "Aileron Trim",
      "Id": "Aileron Trim",
      "Byte": 24,
      "Bit": 0
    },
    {
      "Label": "Indicated Airspeed",
      "Id": "Indicated Airspeed",
      "Byte": 25,
      "Bit": 0
    },
    {
      "Label": "True Airspeed",
      "Id": "True Airspeed",
      "Byte": 26,
      "Bit": 0
    },
    {
      "Label": "Ground Speed",
      "Id": "Ground Speed",
      "Byte": 27,
      "Bit": 0
    },
    {
      "Label": "Rudder Trim",
      "Id": "Rudder Trim",
      "Byte": 28,
      "Bit": 0
    },
    {
      "Label": "Total Heading Input",
      "Id": "Total Heading Input",
      "Byte": 29,
      "Bit": 0
    },
    {
      "Label": "Flap Position",
      "Id": "Flap Position",
      "Byte": 30,
      "Bit": 0
    },
    {
      "Label": "Engine 1 Running",
      "Id": "Engine 1 Running",
      "Byte": 31,
      "Bit": 0
    },
    {
      "Label": "Engine 2 Running",
      "Id": "Engine 2 Running",
      "Byte": 32,
      "Bit": 0
    },
    {
      "Label": "Engine 3 Running",
      "Id": "Engine 3 Running",
      "Byte": 33,
      "Bit": 0
    },
    {
      "Label": "Engine 4 Running",
      "Id": "Engine 4 Running",
      "Byte": 34,
      "Bit": 0
    },
    {
      "Label": "Gear 1 Deploy Ratio",
      "Id": "Gear 1 Deploy Ratio",
      "Byte": 35,
      "Bit": 0
    },
    {
      "Label": "Gear 2 Deploy Ratio",
      "Id": "Gear 2 Deploy Ratio",
      "Byte": 36,
      "Bit": 0
    },
    {
      "Label": "Gear 3 Deploy Ratio",
      "Id": "Gear 3 Deploy Ratio",
      "Byte": 37,
      "Bit": 0
    },
    {
      "Label": "Engine 1 Power",
      "Id": "Engine 1 Power",
      "Byte": 38,
      "Bit": 0
    },
    {
      "Label": "Engine 2 Power",
      "Id": "Engine 2 Power",
      "Byte": 39,
      "Bit": 0
    },
    {
      "Label": "Engine 3 Power",
      "Id": "Engine 3 Power",
      "Byte": 40,
      "Bit": 0
    },
    {
      "Label": "Engine 4 Power",
      "Id": "Engine 4 Power",
      "Byte": 41,
      "Bit": 0
    },
    {
      "Label": "Is In Replay",
      "Id": "Is In Replay",
      "Byte": 42,
      "Bit": 0
    }
  ]
}
