=== MobiFlight/MobiFlight-Connector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": ["InstanceName"],
  "dependentRequired": {
    "Outputs": ["VendorId", "ProductId"]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type"],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": ["Id", "Label", "Byte", "Bit"],
        "properties": {
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required.",
            "type": "number"
          }
        }
      }
    },
    "ProductId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "VendorId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim/vkbsim_gladiator_evo_kg12.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBsim Gladiator EVO KG12",
  "VendorId": "0x231D",
  "ProductId": "0x0600",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "B2 Hat Down"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "B2 Hat Left"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "B2 Hat Right"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "B2 Hat Up"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "B1 Button"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A Trigger"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Paddle Switch"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Ring Finger Button"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Sw1 Up"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Sw1 Down"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "F1"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "F2"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "F3"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "Unused Button 16"
    },
    {
      "Id": 1000,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 1005,
      "Type": "Button",
      "Label": "En1 Down"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim/vkbsim_gladiator_evo_l.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBsim Gladiator EVO L",
  "VendorId": "0x231D",
  "ProductId": "0x0201",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Trigger Soft"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Trigger Hard"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "A2"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "B1"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "D1"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A3 Up"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "A3 Right"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "A3 Down"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "A3 Left"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "A3 Push"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "A4 Up"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "A4 Right"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "A4 Down"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "A4 Left"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "A4 Push"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "C1 Up"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "C1 Right"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "C1 Down"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "C1 Left"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "C1 Push"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "Rapid Fire Up"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Rapid Fire Down"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "Sw1 Up"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "Sw1 Down"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "F1"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "F2"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "F3"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "A1 Push"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "Unused Button 31"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Unused Button 32"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "Unused Button 33"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "Unused Button 34"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "Unused Button 35"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "Unused Button 36"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "Unused Button 37"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "Unused Button 38"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "Unused Button 39"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "Unused Button 40"
    },
    {
      "Id": 1000,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 1005,
      "Type": "Button",
      "Label": "En1 Down"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Red",
      "Id": "SCG.Oval.Red",
      "Byte": 10,
      "Bit": 0
    },
    {
      "Label": "SCG Oval - Green",
      "Id": "SCG.Oval.Green",
      "Byte": 10,
      "Bit": 1
    },
    {
      "Label": "SCG Oval - Blue",
      "Id": "SCG.Oval.Blue",
      "Byte": 10,
      "Bit": 2
    },
    {
      "Label": "SCG Round",
      "Id": "SCG.Round",
      "Byte": 11,
      "Bit": 0
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/winwing/winwing_fcu_efisr.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINWING FCU-320 + EFIS-320R",
  "VendorId": "0x4098",
  "ProductId": "0xBC1E",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "MACH Button"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "LOC Button"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "TRK Button"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "AP1 Button"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "AP2 Button"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A/THR Button"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "EXPED Button"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "METRIC Button"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "APPR Button"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "SPD DEC"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "SPD INC"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "SPD PUSH"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "SPD PULL"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "HDG DEC"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "HDG INC"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "HDG PUSH"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "HDG PULL"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "ALT DEC"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "ALT INC"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "ALT PUSH"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "ALT PULL"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "VS DEC"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "VS INC"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "VS PUSH"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "VS PULL"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "ALT 100"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "ALT 1000"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "FD Button"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "T.O CONFIG Button"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "FD Right Button"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "LS Right Button"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "CSTR Right Button"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "WPT Right Button"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "VORD Right Button"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "NDB Right Button"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "ARPT Right Button"
    },
    {
      "Id": 72,
      "Type": "Button",
      "Label": "BARO Right PUSH"
    },
    {
      "Id": 73,
      "Type": "Button",
      "Label": "BARO Right PULL"
    },
    {
      "Id": 74,
      "Type": "Button",
      "Label": "BARO Right DEC"
    },
    {
      "Id": 75,
      "Type": "Button",
      "Label": "BARO Right INC"
    },
    {
      "Id": 76,
      "Type": "Button",
      "Label": "inHg Right"
    },
    {
      "Id": 77,
      "Type": "Button",
      "Label": "hPa Right"
    },
    {
      "Id": 78,
      "Type": "Button",
      "Label": "ND LS Right"
    },
    {
      "Id": 79,
      "Type": "Button",
      "Label": "ND VOR Right"
    },
    {
      "Id": 80,
      "Type": "Button",
      "Label": "ND NAV Right"
    },
    {
      "Id": 81,
      "Type": "Button",
      "Label": "ND ARC Right"
    },
    {
      "Id": 82,
      "Type": "Button",
      "Label": "ND PLAN Right"
    },
    {
      "Id": 83,
      "Type": "Button",
      "Label": "RANGE 10 Right"
    },
    {
      "Id": 84,
      "Type": "Button",
      "Label": "RANGE 20 Right"
    },
    {
      "Id": 85,
      "Type": "Button",
      "Label": "RANGE 40 Right"
    },
    {
      "Id": 86,
      "Type": "Button",
      "Label": "RANGE 80 Right"
    },
    {
      "Id": 87,
      "Type": "Button",
      "Label": "RANGE 160 Right"
    },
    {
      "Id": 88,
      "Type": "Button",
      "Label": "RANGE 320 Right"
    },
    {
      "Id": 89,
      "Type": "Button",
      "Label": "NAV1 VOR Right"
    },
    {
      "Id": 90,
      "Type": "Button",
      "Label": "NAV1 OFF Right"
    },
    {
      "Id": 91,
      "Type": "Button",
      "Label": "NAV1 ADF Right"
    },
    {
      "Id": 92,
      "Type": "Button",
      "Label": "NAV2 VOR Right"
    },
    {
      "Id": 93,
      "Type": "Button",
      "Label": "NAV2 OFF Right"
    },
    {
      "Id": 94,
      "Type": "Button",
      "Label": "NAV2 ADF Right"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/t.a320_pilot.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "T.A320 Pilot",
  "VendorId":  "0x044F",
  "ProductId": "0x0405",
  "Inputs": [
    {
      "Id": 1,
      "Type":  "Button",
      "Label": "Button 1 - Trigger"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Button 2 - Upper trigger"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "Button 3 - Handle left"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Button 4 - Handle right"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Button 5 - Right front 3"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Button 6 - Right front 2"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Button 7 - Right front 1"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Button 10 - Right back 3"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "Button 9 - Right back 2"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Button 8 - Right back 1"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Button 11 - Left front 1"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Button 12 - Left front 2"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "Button 13 - Left  front 3"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "Button 14 - Left back 3"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "Button 15 - Left back 2"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "Button 16 - Left back 1"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "Button 17 - Slider switch"
    },
    {
      "Id": 48,
      "Type": "Axis",
      "Label": "Axis - Roll"
    },
    {
      "Id": 49,
      "Type": "Axis",
      "Label": "Axis - Pitch"
    },
    {
      "Id": 53,
      "Type": "Axis",
      "Label": "Axis - Grip twist"
    },
    {
      "Id": 54,
      "Type": "Axis",
      "Label": "Axis - Slider"
    }
  ],
  "Outputs": []
}

=== MobiFlight/MobiFlight-Connector/Joysticks/winwing_fcu_efisl_efisr.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINWING FCU-320 + EFIS-320L + EFIS-320R",
  "VendorId": "0x4098",
  "ProductId": "0xBA01",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "MACH Button"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "LOC Button"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "TRK Button"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "AP1 Button"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "AP2 Button"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "A/THR Button"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "EXPED Button"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "METRIC Button"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "APPR Button"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "SPD DEC"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "SPD INC"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "SPD PUSH"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "SPD PULL"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "HDG DEC"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "HDG INC"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "HDG PUSH"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "HDG PULL"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "ALT DEC"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "ALT INC"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "ALT PUSH"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "ALT PULL"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "VS DEC"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "VS INC"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "VS PUSH"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "VS PULL"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "ALT 100"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "ALT 1000"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "FD Button"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "T.O CONFIG Button"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "FD Left Button"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "LS Left Button"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "CSTR Left Button"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "WPT Left Button"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "VORD Left Button"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "NDB Left Button"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "ARPT Left Button"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "BARO Left PUSH"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "BARO Left PULL"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "BARO Left DEC"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "BARO Left INC"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "inHg Left"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "hPa Left"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "ND LS Left"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "ND VOR Left"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "ND NAV Left"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "ND ARC Left"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "ND PLAN Left"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "RANGE 10 Left"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "RANGE 20 Left"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "RANGE 40 Left"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "RANGE 80 Left"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "RANGE 160 Left"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "RANGE 320 Left"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "NAV1 ADF Left"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "NAV1 OFF Left"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "NAV1 VOR Left"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "NAV2 ADF Left"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "NAV2 OFF Left"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "NAV2 VOR Left"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "FD Right Button"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "LS Right Button"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "CSTR Right Button"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "WPT Right Button"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "VORD Right Button"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "NDB Right Button"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "ARPT Right Button"
    },
    {
      "Id": 72,
      "Type": "Button",
      "Label": "BARO Right PUSH"
    },
    {
      "Id": 73,
      "Type": "Button",
      "Label": "BARO Right PULL"
    },
    {
      "Id": 74,
      "Type": "Button",
      "Label": "BARO Right DEC"
    },
    {
      "Id": 75,
      "Type": "Button",
      "Label": "BARO Right INC"
    },
    {
      "Id": 76,
      "Type": "Button",
      "Label": "inHg Right"
    },
    {
      "Id": 77,
      "Type": "Button",
      "Label": "hPa Right"
    },
    {
      "Id": 78,
      "Type": "Button",
      "Label": "ND LS Right"
    },
    {
      "Id": 79,
      "Type": "Button",
      "Label": "ND VOR Right"
    },
    {
      "Id": 80,
      "Type": "Button",
      "Label": "ND NAV Right"
    },
    {
      "Id": 81,
      "Type": "Button",
      "Label": "ND ARC Right"
    },
    {
      "Id": 82,
      "Type": "Button",
      "Label": "ND PLAN Right"
    },
    {
      "Id": 83,
      "Type": "Button",
      "Label": "RANGE 10 Right"
    },
    {
      "Id": 84,
      "Type": "Button",
      "Label": "RANGE 20 Right"
    },
    {
      "Id": 85,
      "Type": "Button",
      "Label": "RANGE 40 Right"
    },
    {
      "Id": 86,
      "Type": "Button",
      "Label": "RANGE 80 Right"
    },
    {
      "Id": 87,
      "Type": "Button",
      "Label": "RANGE 160 Right"
    },
    {
      "Id": 88,
      "Type": "Button",
      "Label": "RANGE 320 Right"
    },
    {
      "Id": 89,
      "Type": "Button",
      "Label": "NAV1 VOR Right"
    },
    {
      "Id": 90,
      "Type": "Button",
      "Label": "NAV1 OFF Right"
    },
    {
      "Id": 91,
      "Type": "Button",
      "Label": "NAV1 ADF Right"
    },
    {
      "Id": 92,
      "Type": "Button",
      "Label": "NAV2 VOR Right"
    },
    {
      "Id": 93,
      "Type": "Button",
      "Label": "NAV2 OFF Right"
    },
    {
      "Id": 94,
      "Type": "Button",
      "Label": "NAV2 ADF Right"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/winwing_pap3.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINWING PAP3",
  "VendorId": "0x4098",
  "ProductId": "0xBF0F",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "N1 Button"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Speed Button"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "VNAV Button"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "LVL CHG Button"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "HDG SEL Button"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "LNAV Button"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "VOR LOC Button"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "APP Button"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "ALT HLD Button"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "V/S Button"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "CMD A Button"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "CWS A Button"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "CMD B Button"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "CWS B Button"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "C/O Button"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "SP INTV Button"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "ALT INTV Button"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "Capt CRS DEC"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "Capt CRS INC"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "IAS/MACH DEC"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "IAS/MACH INC"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "Heading DEC"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "Heading INC"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "Altitude DEC"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "Altitude INC"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "FO CRS DEC"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "FO CRS INC"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "FD L Switch On"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "FD L Switch Off"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "FD R Switch On"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "FD R Switch Off"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Disengage Bar Up"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "Disengage Bar Down"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "Bank Angle 10"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "Bank Angle 15"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "Bank Angle 20"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "Bank Angle 25"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "Bank Angle 30"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "V/S DEC"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "V/S INC"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "A/T ARM"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "A/T OFF"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/octavi.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "Octavi",
  "VendorId": "0x04D8",
  "ProductId": "0xE6D6",
  "Inputs": [
    {
      "Id": 0,
      "Type": "Button",
      "Label": "COM1"
    },
    {
      "Id": 1,
      "Type": "Button",
      "Label": "COM2"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "NAV1"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "NAV2"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "XPDR"
    }
  ],
  "Outputs": [
    {
      "Label": "AP Master",
      "Id": "AP.AP",
      "Byte": 1,
      "Bit": 0
    },
    {
      "Label": "AP HDG",
      "Id": "AP.HDG",
      "Byte": 1,
      "Bit": 1
    },
    {
      "Label": "AP NAV",
      "Id": "AP.NAV",
      "Byte": 1,
      "Bit": 2
    },
    {
      "Label": "AP APR",
      "Id": "AP.APR",
      "Byte": 1,
      "Bit": 3
    },
    {
      "Label": "AP ALT",
      "Id": "AP.ALT",
      "Byte": 1,
      "Bit": 4
    },
    {
      "Label": "AP VS",
      "Id": "AP.VS",
      "Byte": 1,
      "Bit": 5
    }

  ]
}
