=== MobiFlight/MobiFlight-Connector/Joysticks/mfjoystick.schema.json
{
  "definitions": {},
  "$schema": "https://json-schema.org/draft/2019-09/schema#",
  "$id": "https://mobiflight.com/hid.schema.json",
  "title": "Root",
  "type": "object",
  "required": ["InstanceName"],
  "dependentRequired": {
    "Outputs": ["VendorId", "ProductId"]
  },
  "properties": {
    "InstanceName": {
      "$id": "#root/InstanceName",
      "title": "InstanceName",
      "type": "string",
      "description": "Instance name for the device. Required. This is used to match the definition with a connected device."
    },
    "Inputs": {
      "$id": "#root/Inputs",
      "title": "Inputs",
      "description": "List of inputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Inputs/items",
        "title": "Items",
        "type": "object",
        "required": [ "Id", "Label", "Type"],
        "properties": {
          "Id": {
            "$id": "#root/Inputs/items/Id",
            "title": "Id",
            "description": "The input's unique identifier on the joystick. Required.",
            "type": "integer"
          },
          "Label": {
            "$id": "#root/Inputs/items/Label",
            "title": "Label",
            "description": "Friendly label for the input. Required.",
            "type": "string"
          },
          "Type": {
            "$id": "#root/Inputs/items/Type",
            "title": "Type",
            "description": "The input's type. Supported values: Button, Axis.",
            "type": "string",
            "enum": [ "Button", "Axis" ]
          }
        }
      }
    },
    "Outputs": {
      "$id": "#root/Outputs",
      "title": "Outputs",
      "description": "List of outputs supported by the device. Optional.",
      "type": "array",
      "default": [],
      "items": {
        "$id": "#root/Outputs/items",
        "title": "Items",
        "type": "object",
        "required": ["Id", "Label", "Byte", "Bit"],
        "properties": {
          "Id": {
            "$id": "#root/Outputs/items/Id",
            "title": "Id",
            "description": "The unique identifier for the output. Required.",
            "type": "string"
          },
          "Label": {
            "$id": "#root/Outputs/items/Label",
            "title": "Label",
            "description": "Label for the output. Required.",
            "type": "string"
          },
          "Byte": {
            "$id": "#root/Outputs/items/Byte",
            "title": "Byte",
            "description": "Byte location of the output. Required.",
            "type": "number"
          },
          "Bit": {
            "$id": "#root/Outputs/items/Bit",
            "title": "Bit",
            "description": "Bit location within the byte of the output. Required.",
            "type": "number"
          }
        }
      }
    },
    "ProductId": {
      "$id": "#Root/VendorId",
      "title": "VendorId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB VendorId as a hexadcimal, e.g. `0x123A`. Required if Outputs are provided."
    },
    "VendorId": {
      "$id": "#Root/ProductId",
      "title": "ProductId",
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]+$",
      "description": "The device's USB ProductId as a hexadecimal, e.g. `0x234A`. Required if Outputs are provided."
    }
  }
}

=== MobiFlight/MobiFlight-Connector/Joysticks/winwing_pfp7_observer.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINWING PFP-7-OBSERVER",
  "VendorId": "0x4098",
  "ProductId": "0xBB3B",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Line-Select-Key 1L"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Line-Select-Key 2L"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "Line-Select-Key 3L"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Line-Select-Key 4L"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Line-Select-Key 5L"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Line-Select-Key 6L"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Line Select Key 1R"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Line Select Key 2R"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "Line Select Key 3R"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Line Select Key 4R"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Line Select Key 5R"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Line Select Key 6R"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "Init/Ref Button"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "RTE Button"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "CLB Button"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "CRZ Button"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "DES Button"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "BRT- Button"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "BRT+ Button"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "MENU Button"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "LEGS Button"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "DEP/ARR Button"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "HOLD Button"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "PROG Button"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "EXEC Button"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "N1/LIMIT Button"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "FIX Button"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "PREV PAGE Button"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "NEXT PAGE Button"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "1 Button"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "2 Button"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "3 Button"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "4 Button"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "5 Button"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "6 Button"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "7 Button"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "8 Button"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "9 Button"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": ". Button"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "0 Button"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "+/- Button"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": "A Button"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "B Button"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "C Button"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "D Button"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "E Button"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "F Button"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "G Button"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "H Button"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "I Button"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "J Button"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "K Button"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "L Button"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "M Button"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "N Button"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "O Button"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "P Button"
    },
    {
      "Id": 58,
      "Type": "Button",
      "Label": "Q Button"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "R Button"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "S Button"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "T Button"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "U Button"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "V Button"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "W Button"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "X Button"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "Y Button"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "Z Button"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "SP Button"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "DEL Button"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "/ Button"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "CLR Button"
    },
    {
      "Id": 51,
      "Type": "Axis",
      "Label": "Light Sensor 1"
    },
    {
      "Id": 52,
      "Type": "Axis",
      "Label": "Light Sensor 2"
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim/vkbsim_nxt_thq.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBSim NXT THQ",
  "VendorId": "0x231D",
  "ProductId": "0x2210",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "THQ A1"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "THQ A2"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "THQ A3"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "THQ A4"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "THQ B1"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "THQ C1"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "THQ C2"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "THQ B2"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim/vkbsim_gladiator_evo_f14.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBsim Gladiator EVO F14",
  "VendorId": "0x231D",
  "ProductId": "0x0A00",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Trigger Soft"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Trigger Hard"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "Red Button"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Weapon Select Push"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Side Button"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Paddle Switch"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Pinky Switch"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Hat Push"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "Hat Down NU"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Hat Left LWD"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Hat Right RWD"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Hat Up ND"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "Weapon Select SP PH"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "Weapon Select SW"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "Weapon Select Gun"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "Weapon Select Off"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "En1 Down"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "Sw1 Up"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "Sw1 Down"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "F1"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "F2"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "F3"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "Unused Button 24"
    },
    {
      "Id": 1000,
      "Type": "Button",
      "Label": "En1 Up"
    },
    {
      "Id": 1005,
      "Type": "Button",
      "Label": "En1 Down"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/vkbsim_nxt_sem.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "VKBSim NXT SEM",
  "VendorId": "0x231D",
  "ProductId": "0x2204",
  "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "SEM A1"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "SEM A2"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "SEM B1"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "SEM B2"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "SEM B3"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "SEM Sw1 Up"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "SEM Sw1 Center"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "SEM Sw1 Down"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "SEM Sw2 Up"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "SEM Sw2 Center"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "SEM Sw2 Down"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "SEM Start"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "SEM Mode 1"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "SEM Mode 2"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "SEM Mode 3"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "SEM Mode 4"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "SEM C1"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "SEM Flaps 3"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "SEM Flaps 2"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "SEM Flaps 1"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "SEM Flaps 0"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "SEM Gear Down"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "SEM Gear Neutral"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "SEM Gear Up"
    }
  ],
  "Outputs": [
    {
      "Label": "Sys - Blue",
      "Id": "Sys.Blue",
      "Byte": 0,
      "Bit": 0
    },
    {
      "Label": "Sys - Red",
      "Id": "Sys.Red",
      "Byte": 0,
      "Bit": 1
    },
    {
      "Label": "SEM A1 - Green",
      "Id": "SEM.A1.Green",
      "Byte": 10,
      "Bit": 0
    },
    {
      "Label": "SEM A1 - Red",
      "Id": "SEM.A1.Red",
      "Byte": 10,
      "Bit": 1
    },
    {
      "Label": "SEM A2 - Green",
      "Id": "SEM.A2.Green",
      "Byte": 11,
      "Bit": 0
    },
    {
      "Label": "SEM A2 - Red",
      "Id": "SEM.A2.Red",
      "Byte": 11,
      "Bit": 1
    },
    {
      "Label": "SEM B1 - Green",
      "Id": "SEM.B1.Green",
      "Byte": 12,
      "Bit": 0
    },
    {
      "Label": "SEM B1 - Red",
      "Id": "SEM.B1.Red",
      "Byte": 12,
      "Bit": 1
    },
    {
      "Label": "SEM B2 - Green",
      "Id": "SEM.B2.Green",
      "Byte": 13,
      "Bit": 0
    },
    {
      "Label": "SEM B2 - Red",
      "Id": "SEM.B2.Red",
      "Byte": 13,
      "Bit": 1
    },
    {
      "Label": "SEM B3 - Green",
      "Id": "SEM.B3.Green",
      "Byte": 14,
      "Bit": 0
    },
    {
      "Label": "SEM B3 - Red",
      "Id": "SEM.B3.Red",
      "Byte": 14,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Left - Green",
      "Id": "SEM.GearL.Green",
      "Byte": 15,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Left - Red",
      "Id": "SEM.GearL.Red",
      "Byte": 15,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Center - Green",
      "Id": "SEM.GearC.Green",
      "Byte": 16,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Center - Red",
      "Id": "SEM.GearC.Red",
      "Byte": 16,
      "Bit": 1
    },
    {
      "Label": "SEM Gear Right - Green",
      "Id": "SEM.GearR.Green",
      "Byte": 17,
      "Bit": 0
    },
    {
      "Label": "SEM Gear Right - Red",
      "Id": "SEM.GearR.Red",
      "Byte": 17,
      "Bit": 1
    }
  ]
}

=== MobiFlight/MobiFlight-Connector/Joysticks/winwing/winwing_mcdu_captain.joystick.json
{
  "$schema": "./mfjoystick.schema.json",
  "InstanceName": "WINWING MCDU-32-CAPTAIN",
  "VendorId": "0x4098",
  "ProductId": "0xBB36",
    "Inputs": [
    {
      "Id": 1,
      "Type": "Button",
      "Label": "Line-Select-Key 1L"
    },
    {
      "Id": 2,
      "Type": "Button",
      "Label": "Line-Select-Key 2L"
    },
    {
      "Id": 3,
      "Type": "Button",
      "Label": "Line-Select-Key 3L"
    },
    {
      "Id": 4,
      "Type": "Button",
      "Label": "Line-Select-Key 4L"
    },
    {
      "Id": 5,
      "Type": "Button",
      "Label": "Line-Select-Key 5L"
    },
    {
      "Id": 6,
      "Type": "Button",
      "Label": "Line-Select-Key 6L"
    },
    {
      "Id": 7,
      "Type": "Button",
      "Label": "Line-Select-Key 1R"
    },
    {
      "Id": 8,
      "Type": "Button",
      "Label": "Line-Select-Key 2R"
    },
    {
      "Id": 9,
      "Type": "Button",
      "Label": "Line-Select-Key 3R"
    },
    {
      "Id": 10,
      "Type": "Button",
      "Label": "Line-Select-Key 4R"
    },
    {
      "Id": 11,
      "Type": "Button",
      "Label": "Line-Select-Key 5R"
    },
    {
      "Id": 12,
      "Type": "Button",
      "Label": "Line-Select-Key 6R"
    },
    {
      "Id": 13,
      "Type": "Button",
      "Label": "DIR Button"
    },
    {
      "Id": 14,
      "Type": "Button",
      "Label": "PROG Button"
    },
    {
      "Id": 15,
      "Type": "Button",
      "Label": "PERF Button"
    },
    {
      "Id": 16,
      "Type": "Button",
      "Label": "INIT Button"
    },
    {
      "Id": 17,
      "Type": "Button",
      "Label": "DATA Button"
    },
    {
      "Id": 18,
      "Type": "Button",
      "Label": "Blank Button R"
    },
    {
      "Id": 19,
      "Type": "Button",
      "Label": "BRT Button"
    },
    {
      "Id": 20,
      "Type": "Button",
      "Label": "F-PLN Button"
    },
    {
      "Id": 21,
      "Type": "Button",
      "Label": "RAD NAV Button"
    },
    {
      "Id": 22,
      "Type": "Button",
      "Label": "FUEL PRED Button"
    },
    {
      "Id": 23,
      "Type": "Button",
      "Label": "SEC F-PLN Button"
    },
    {
      "Id": 24,
      "Type": "Button",
      "Label": "ATC COMM Button"
    },
    {
      "Id": 25,
      "Type": "Button",
      "Label": "MCDU MENU Button"
    },
    {
      "Id": 26,
      "Type": "Button",
      "Label": "DIM Button"
    },
    {
      "Id": 27,
      "Type": "Button",
      "Label": "AIRPORT Button"
    },
    {
      "Id": 28,
      "Type": "Button",
      "Label": "Blank Button L"
    },
    {
      "Id": 29,
      "Type": "Button",
      "Label": "Left-Arrow Button"
    },
    {
      "Id": 30,
      "Type": "Button",
      "Label": "Up-Arrow Button"
    },
    {
      "Id": 31,
      "Type": "Button",
      "Label": "Right-Arrow Button"
    },
    {
      "Id": 32,
      "Type": "Button",
      "Label": "Down-Arrow Button"
    },
    {
      "Id": 33,
      "Type": "Button",
      "Label": "1 Button"
    },
    {
      "Id": 34,
      "Type": "Button",
      "Label": "2 Button"
    },
    {
      "Id": 35,
      "Type": "Button",
      "Label": "3 Button"
    },
    {
      "Id": 36,
      "Type": "Button",
      "Label": "4 Button"
    },
    {
      "Id": 37,
      "Type": "Button",
      "Label": "5 Button"
    },
    {
      "Id": 38,
      "Type": "Button",
      "Label": "6 Button"
    },
    {
      "Id": 39,
      "Type": "Button",
      "Label": "7 Button"
    },
    {
      "Id": 40,
      "Type": "Button",
      "Label": "8 Button"
    },
    {
      "Id": 41,
      "Type": "Button",
      "Label": "9 Button"
    },
    {
      "Id": 42,
      "Type": "Button",
      "Label": ". Button"
    },
    {
      "Id": 43,
      "Type": "Button",
      "Label": "0 Button"
    },
    {
      "Id": 44,
      "Type": "Button",
      "Label": "+/- Button"
    },
    {
      "Id": 45,
      "Type": "Button",
      "Label": "A Button"
    },
    {
      "Id": 46,
      "Type": "Button",
      "Label": "B Button"
    },
    {
      "Id": 47,
      "Type": "Button",
      "Label": "C Button"
    },
    {
      "Id": 48,
      "Type": "Button",
      "Label": "D Button"
    },
    {
      "Id": 49,
      "Type": "Button",
      "Label": "E Button"
    },
    {
      "Id": 50,
      "Type": "Button",
      "Label": "F Button"
    },
    {
      "Id": 51,
      "Type": "Button",
      "Label": "G Button"
    },
    {
      "Id": 52,
      "Type": "Button",
      "Label": "H Button"
    },
    {
      "Id": 53,
      "Type": "Button",
      "Label": "I Button"
    },
    {
      "Id": 54,
      "Type": "Button",
      "Label": "J Button"
    },
    {
      "Id": 55,
      "Type": "Button",
      "Label": "K Button"
    },
    {
      "Id": 56,
      "Type": "Button",
      "Label": "L Button"
    },
    {
      "Id": 57,
      "Type": "Button",
      "Label": "M Button"
	},
    {
      "Id": 58,
      "Type": "Button",
      "Label": "N Button"
    },
    {
      "Id": 59,
      "Type": "Button",
      "Label": "O Button"
    },
    {
      "Id": 60,
      "Type": "Button",
      "Label": "P Button"
    },
    {
      "Id": 61,
      "Type": "Button",
      "Label": "Q Button"
    },
    {
      "Id": 62,
      "Type": "Button",
      "Label": "R Button"
    },
    {
      "Id": 63,
      "Type": "Button",
      "Label": "S Button"
    },
    {
      "Id": 64,
      "Type": "Button",
      "Label": "T Button"
    },
    {
      "Id": 65,
      "Type": "Button",
      "Label": "U Button"
    },
    {
      "Id": 66,
      "Type": "Button",
      "Label": "V Button"
    },
    {
      "Id": 67,
      "Type": "Button",
      "Label": "W Button"
    },
    {
      "Id": 68,
      "Type": "Button",
      "Label": "X Button"
    },
    {
      "Id": 69,
      "Type": "Button",
      "Label": "Y Button"
    },
    {
      "Id": 70,
      "Type": "Button",
      "Label": "Z Button"
    },
    {
      "Id": 71,
      "Type": "Button",
      "Label": "/ Button"
    },
    {
      "Id": 72,
      "Type": "Button",
      "Label": "SP Button"
    },
    {
      "Id": 73,
      "Type": "Button",
      "Label": "OVFY Button"
    },
    {
      "Id": 74,
      "Type": "Button",
      "Label": "CLR Button"
    },
	{
      "Id": 51,
      "Type": "Axis",
      "Label": "Light Sensor 1"
    },
	{
      "Id": 52,
      "Type": "Axis",
      "Label": "Light Sensor 2"
    }
  ]
}
